name:               "Radiofisik"
description:        "my knowledge base"

url:                ""
author:             "radiofisik"
email:              "mail@radiofisik.ru"
gravatar_hash:      "ddf1a8cb93900b0cb7b86d96663a54d4"
twitter:            "radiofisik"
email:              "mail@radiofisik.ru"
github:             "radiofisik"
pinterest:          "0liks8jl05hcpyb1chvg0b9teugvwf"


disqus_shortname:   ""

background:         "http://www.hdiphonewallpapers.us/phone-wallpapers/iphone-6s-wallpaper-1-1080x1920/iphone-6s-wallpaper-HD-320o6thl-1080x1920.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
#  - name:           "About"
#    href:           "/about"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
