name:               "Radiofisik's homepage"
description:        "my knowledge base"

url:                ""
author:             "radiofisik"
email:              "mail@radiofisik.ru"
gravatar_hash:      "ddf1a8cb93900b0cb7b86d96663a54d4"
twitter:            "radiofisik"
email:              "mail@radiofisik.ru"
github:             "radiofisik"
pinterest:          "0liks8jl05hcpyb1chvg0b9teugvwf"
linkedin:           ""
facebook:           ""

disqus_shortname:   ""

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
